### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by liamnotenough** [snail23/ironpedal#1]
​​​Hello
This is Liam from PCBWay, deeply impressed by this project which is novel and creative,
I’d like to sponsor your project by providing free PCB prototyping,
All I ask for in return is a slight promotion or review of our quality or service.
Would you be interested in partnering up? Contact me: liam@pcbway.com

**Comment by snail23** [comment]
Hey Liam, I went ahead and sent you an email. I'll close this issue for now so we can talk through email. Glad you liked the project!
