### ISSUE TITLE
OLED screen connection

### ISSUE THREAD

**Issue by sballano** [snail23/ironpedal#2]
Great project!

I just finished it and it is quite impressive! I just had to dig a bit through the code to find out how the OLED screen is connected to the Daisy and I think if you could put that on the README it would be of great help for other people building the pedal, specially if they don't code:

| Screen pin   | Daisy signal | pin number |
|--------------|--------------|------------|
| Vcc          | 3V3 dig      |         38 |
| GND          | DGND         |         40 |
| DIN          | MOSI/D6      |          7 |
| CLK          | SCLK/D2      |          3 |
| CS           | CS/D3        |          4 |
| DC           | MISO/D1      |          2 |
| RST          | D30          |         37 |

**Comment by snail23** [comment]
Hey there, I'm glad you enjoyed the build! Nice catch on the OLED connections, that should have been more clear on my end so I'm sorry you had to spend a bunch of time digging through all of that. I've been there lol.

I've gone ahead and added this to the readme under step 6 of the soldering instructions for future people, cheers!
